# This file was generated by GoReleaser. DO NOT EDIT.
cask "spotdb" do
  name "spotdb"
  desc "SpotDB - A fast, lightweight data analysis tool"
  homepage "https://github.com/aliengiraffe/spotdb"
  version "1.20-demo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spotdb"

  on_macos do
    on_arm do
      url "https://github.com/aliengiraffe/spotdb/releases/download/v#{version}/spotdb_#{version}_darwin_arm64.tar.gz"
      sha256 "0240a3b910ae8bfc4a0486cdd2bf7b32dca10bf1b3cf5ef4cad0ef9b386d34e4"
    end
  end

  caveats do
    "SpotDB is a command-line tool for data analysis."
    "Run 'spotdb -version' to verify installation."
  end

  # No zap stanza required
end
