# This file was generated by GoReleaser. DO NOT EDIT.
cask "spotdb" do
  name "spotdb"
  desc "SpotDB - A fast, lightweight data analysis tool"
  homepage "https://github.com/aliengiraffe/spotdb"
  version "1.11-demo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spotdb"

  on_linux do
    on_arm do
      url "https://github.com/aliengiraffe/spotdb/releases/download/v#{version}/spotdb_#{version}_linux_arm64.tar.gz"
      sha256 "d9d207540bc5d504b448aaa7b84024c80d7e93b131443e9cc61a3677dbcce54f"
    end
  end

  caveats do
    "SpotDB is a command-line tool for data analysis."
    "Run 'spotdb -version' to verify installation."
  end

  # No zap stanza required
end
