# This file was generated by GoReleaser. DO NOT EDIT.
cask "spotdb" do
  name "spotdb"
  desc "SpotDB - A fast, lightweight data analysis tool"
  homepage "https://github.com/aliengiraffe/spotdb"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spotdb"

  on_macos do
    on_arm do
      url "https://github.com/aliengiraffe/spotdb/releases/download/v#{version}/spotdb_#{version}_darwin_arm64.tar.gz"
      sha256 "c33e3c0b5bbcf0ba8b336499b6dc4c5ca18722e06d9b048b2559de3609856122"
    end
  end

  caveats do
    "SpotDB is a command-line tool for data analysis."
    "Run 'spotdb -version' to verify installation."
  end

  # No zap stanza required
end
