# This file was generated by the Vigilante nightly workflow. DO NOT EDIT.
cask "vigilante-nightly" do
  name "vigilante nightly"
  desc "Autonomous GitHub issue runner for headless coding agents"
  homepage "https://github.com/aliengiraffe/vigilante"
  version "0.0.0-nightly.20260321162154.e1d581557496"

  livecheck do
    skip "Rolling prerelease updated from main."
  end

  binary "vigilante"

  on_macos do
    on_intel do
      url "https://github.com/aliengiraffe/vigilante/releases/download/main-nightly/vigilante_0.0.0-nightly.20260321162154.e1d581557496_macOS_amd64.tar.gz"
      sha256 "c629e7c58979e3c56ec1e9aff1537cde8e1eab558047a472c11c65c03071ce54"
    end
    on_arm do
      url "https://github.com/aliengiraffe/vigilante/releases/download/main-nightly/vigilante_0.0.0-nightly.20260321162154.e1d581557496_macOS_arm64.tar.gz"
      sha256 "95e24be3e97458220680014b36a715703d3937d99350399a1ae80a61351e92e3"
    end

    postflight do
      system_command "/usr/bin/xattr",
                     args:         ["-dr", "com.apple.provenance", staged_path.to_s],
                     must_succeed: false
      system_command "/usr/bin/xattr",
                     args:         ["-dr", "com.apple.quarantine", staged_path.to_s],
                     must_succeed: false
      system_command "/usr/bin/codesign",
                     args:         ["--force", "--sign", "-", "#{staged_path}/vigilante"],
                     must_succeed: false
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aliengiraffe/vigilante/releases/download/main-nightly/vigilante_0.0.0-nightly.20260321162154.e1d581557496_Linux_amd64.tar.gz"
      sha256 "eb4c23787c1580a1b9464ade9074dab1db14363979b832ce16f26798312ad9d4"
    end
  end

  # No zap stanza required
end
