# This file was generated by GoReleaser. DO NOT EDIT.
cask "vigilante" do
  name "vigilante"
  desc "Autonomous GitHub issue runner for headless coding agents"
  homepage "https://github.com/aliengiraffe/vigilante"
  version "1.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vigilante"

  on_macos do
    on_intel do
      url "https://github.com/aliengiraffe/vigilante/releases/download/v#{version}/vigilante_#{version}_macOS_amd64.tar.gz"
      sha256 "4072307e05ab28f4376b9b7d64ff495e5bb87df81d96d317660ab1e63a5bcae8"
    end
    on_arm do
      url "https://github.com/aliengiraffe/vigilante/releases/download/v#{version}/vigilante_#{version}_macOS_arm64.tar.gz"
      sha256 "96c7386a2253ffc60537a4efe3b652d94bd7ac1e20b30d6d8d8b1fa33ae75573"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aliengiraffe/vigilante/releases/download/v#{version}/vigilante_#{version}_Linux_amd64.tar.gz"
      sha256 "a576d64132ff8b06e9437c1ebf97d4469181e64f3cdd42bffeb8981140f43a08"
    end
  end

  # No zap stanza required
end
