# This file was generated by the Vigilante nightly workflow. DO NOT EDIT.
cask "vigilante-nightly" do
  name "vigilante nightly"
  desc "Autonomous GitHub issue runner for headless coding agents"
  homepage "https://github.com/aliengiraffe/vigilante"
  version "0.0.0-nightly.20260321220055.aa61fda81637"

  livecheck do
    skip "Rolling prerelease updated from main."
  end

  binary "vigilante"

  on_macos do
    on_intel do
      url "https://github.com/aliengiraffe/vigilante/releases/download/main-nightly/vigilante_0.0.0-nightly.20260321220055.aa61fda81637_macOS_amd64.tar.gz"
      sha256 "29d0f244c5a2a540538b2e5266802067f110cba23ed9b459288adb7703164efe"
    end
    on_arm do
      url "https://github.com/aliengiraffe/vigilante/releases/download/main-nightly/vigilante_0.0.0-nightly.20260321220055.aa61fda81637_macOS_arm64.tar.gz"
      sha256 "d6afc22bc03f52529217dd29d810fbeb381bb4a13bd9fa4a877362c569a8fb2b"
    end

    postflight do
      system_command "/usr/bin/xattr",
                     args:         ["-dr", "com.apple.provenance", staged_path.to_s],
                     must_succeed: false
      system_command "/usr/bin/xattr",
                     args:         ["-dr", "com.apple.quarantine", staged_path.to_s],
                     must_succeed: false
      system_command "/usr/bin/codesign",
                     args:         ["--force", "--sign", "-", "#{staged_path}/vigilante"],
                     must_succeed: false
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aliengiraffe/vigilante/releases/download/main-nightly/vigilante_0.0.0-nightly.20260321220055.aa61fda81637_Linux_amd64.tar.gz"
      sha256 "dd3dcb06be05a6f01775a07613a725dc5af66ca7b680768f3ead78dc395d266c"
    end
  end

  # No zap stanza required
end
