# This file was generated by the Vigilante nightly workflow. DO NOT EDIT.
cask "vigilante-nightly" do
  name "vigilante nightly"
  desc "Autonomous GitHub issue runner for headless coding agents"
  homepage "https://github.com/aliengiraffe/vigilante"
  version "0.0.0-nightly.20260401214439.93d975a363f7"

  livecheck do
    skip "Rolling prerelease updated from main."
  end

  binary "vigilante"

  on_macos do
    on_intel do
      url "https://github.com/aliengiraffe/vigilante/releases/download/main-nightly/vigilante_0.0.0-nightly.20260401214439.93d975a363f7_macOS_amd64.tar.gz"
      sha256 "d8782b22202e4a8a0161e96b08c35b0b0343acc722933de620901a58247956b1"
    end
    on_arm do
      url "https://github.com/aliengiraffe/vigilante/releases/download/main-nightly/vigilante_0.0.0-nightly.20260401214439.93d975a363f7_macOS_arm64.tar.gz"
      sha256 "d7436f3c95caea51a7be7725dfe42e2c097b8d4ed95c109616d78c65b5ef531a"
    end

    postflight do
      system_command "/usr/bin/xattr",
                     args:         ["-dr", "com.apple.provenance", staged_path.to_s],
                     must_succeed: false
      system_command "/usr/bin/xattr",
                     args:         ["-dr", "com.apple.quarantine", staged_path.to_s],
                     must_succeed: false
      system_command "/usr/bin/codesign",
                     args:         ["--force", "--sign", "-", "#{staged_path}/vigilante"],
                     must_succeed: false
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aliengiraffe/vigilante/releases/download/main-nightly/vigilante_0.0.0-nightly.20260401214439.93d975a363f7_Linux_amd64.tar.gz"
      sha256 "2f51a4c5889ac4a84ae9b42224b43905143f5f48301efcc720d74e59c2d0ff9c"
    end
  end

  # No zap stanza required
end
