# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deputy < Formula
  desc "Deputy is a centralized management tool for MCP (Model Context Protocol) servers across multiple AI tools."
  homepage "https://github.com/aliengiraffe/deputy"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aliengiraffe/deputy/releases/download/0.0.1/deputy_0.0.1_darwin_amd64.tar.gz"
      sha256 "1dd2ecb169ec7a22ac0b93750c3c311e692dab3cbf7c6dc7094433daa26105a5"

      def install
        bin.install "deputy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aliengiraffe/deputy/releases/download/0.0.1/deputy_0.0.1_darwin_arm64.tar.gz"
      sha256 "92926964845445a9024be08d8562950db054a7aa73f441e5db94becf351ee027"

      def install
        bin.install "deputy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aliengiraffe/deputy/releases/download/0.0.1/deputy_0.0.1_linux_amd64.tar.gz"
      sha256 "4c4d5ff1e513bbd59e0c0f4fd456b59440b8c6e39422e3787ff6faebdcb4ab54"
      def install
        bin.install "deputy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aliengiraffe/deputy/releases/download/0.0.1/deputy_0.0.1_linux_arm64.tar.gz"
      sha256 "9a793f6c2171f30fd134ebd6aa37030f21fba819f881188324f5073726e987e1"
      def install
        bin.install "deputy"
      end
    end
  end

  test do
    system "#{bin}/deputy version"
  end
end
